// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKG2NL-mGA6_KWA5b5-ikqgeH_WVVj6Ck',
    appId: '1:122524339454:web:db80bb796f3b51f6ed69af',
    messagingSenderId: '122524339454',
    projectId: 'finance-goal-tracker-ab8fa',
    authDomain: 'finance-goal-tracker-ab8fa.firebaseapp.com',
    storageBucket: 'finance-goal-tracker-ab8fa.appspot.com',
    measurementId: 'G-BFCN1NJ84W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr4sxhfAWuQrOoYq2KQaNNyPaywmwCCk8',
    appId: '1:122524339454:android:b8c8c3fa05ec9c14ed69af',
    messagingSenderId: '122524339454',
    projectId: 'finance-goal-tracker-ab8fa',
    storageBucket: 'finance-goal-tracker-ab8fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAydNDjp3uB3BiBpxR_s1rCh_I2kXjGp70',
    appId: '1:122524339454:ios:2c6b6e5870ac76c7ed69af',
    messagingSenderId: '122524339454',
    projectId: 'finance-goal-tracker-ab8fa',
    storageBucket: 'finance-goal-tracker-ab8fa.appspot.com',
    iosBundleId: 'com.example.expenseTrack',
  );
}
